mysite/mortgage/urls.py
from django.urls import path
from .import views
from django.views.generic import TemplateView

app_name='mortgage'
urlpatterns=[
	path('',views.loan_details_view,name='loan_details_view'),
	path('balance_func/',views.remaining_balance_func,name='balance_func'),
	path('<int:id>/',views.monthly_payment_func,name='monthly_payment_func'),
	path('monthly_expenses/',views.expenses_func,name='monthly_expenses'),
	path('monthly_payment_func3/',views.monthly_payment_func3,name='monthly_payment_func3'),
	path('Yearly_Mortgage_Balance/',views.Yearly_Mortagage_Balance,name='Yearly_Mortgage_Balance'),
	path('fibonacci_number/',views.fibonacci_number,name='Fibonacci_Number'),
	path('media_func/',views.media_func,name='media_func'),
	path('file_store/',views.file_store,name='file_store'),
	path('post/',views.FileFieldView.post,name='post'),
	path('image_func/',views.image_func,name='image_func'),
	path('login/',views.user_login,name='login'),
	path('file_response/',views.file_response,name='file_response'),
	path('contact/',TemplateView.as_view(template_name="mortgage/contact.html")),
	]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('mortgage/',include('mortgage.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views
app_name='polls'
urlpatterns = [
        path('',views.Indexview.as_view(),name='index'),
	    path('<int:question_id>/',views.detail,name='detail'),
 	    path('<int:question_id>/results/',views.results,name='results'),
	    path('<int:question_id>/vote/',views.vote,name='vote'),
	]

mysite/mortgage/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class monthly_payment(models.Model):
	id = models.AutoField(primary_key=True)
	principal=models.IntegerField()
	interest=models.DecimalField(max_digits=5,decimal_places=3)
	duration=models.IntegerField()
	payment=models.FloatField(default=0)
	
	def __int__(self):
		return self.principal
class Remaining_Balance(models.Model):
	id = models.AutoField(primary_key=True)
	principal           =models.IntegerField()
	interest            =models.FloatField()
	duration            =models.IntegerField()
	no_of_payments_made =models.IntegerField(default=0)
	amount_due          =models.FloatField()
	
	def __int__(self):
		return (self.principal,self.interest,self.duration)

class Monthly_Expenses(models.Model):
	id = models.AutoField(primary_key=True)
	item      = models.CharField(max_length=20)
	price     = models.FloatField()
	pub_date  = models.DateField(default=timezone.now())
	total     = models.DecimalField(max_digits=6,decimal_places=2,default=0)
	
	def __int__(self):
		return self.item

class Fibonacci_number(models.Model):
	id = models.AutoField(primary_key=True)
	number =models.IntegerField()

class media_store(models.Model):
	id = models.AutoField(primary_key=True)
	title=models.CharField(max_length=20)
	file=models.FileField()

class File_Upload(models.Model):
	id = models.AutoField(primary_key=True)
	Title=models.CharField(max_length=20)
	File=models.FileField()

class Image_Upload(models.Model):
	id = models.AutoField(primary_key=True)
	Name=models.CharField(max_length=20)
	#Image=models.ImageField()

class user_login(models.Model):
	id = models.AutoField(primary_key=True)
	username=models.CharField(max_length=20)
	password=models.CharField(max_length=20)

class Car(models.Model):
	id = models.AutoField(primary_key=True)
	name=models.CharField(max_length=255)
	price=models.DecimalField(max_digits=5,decimal_places=3)
	#image=models.ImageField(upload_to='cars')

mysite/mortgage/forms.py
from django import forms

from .models import monthly_payment,media_store,File_Upload,user_login

class Monthly_paymentForm(forms.ModelForm):
	class Meta:
		model=monthly_payment
		fields=[
			'principal',
			'interest',
			'duration',
			'payment'
 			]
			

class Monthly_payment_raw_Form(forms.Form):
	principal             =forms.IntegerField()
	interest              =forms.FloatField()
	duration              =forms.IntegerField()
	

class Remaining_Balance_Raw_Form(forms.Form):
	principal             =forms.IntegerField()
	interest              =forms.FloatField()
	duration              =forms.IntegerField()
	no_of_payments_made   =forms.IntegerField()

class Monthly_Expenses_Raw_Form(forms.Form):
	item  =forms.CharField()
	price =forms.FloatField()
	pub_date  =forms.DateField()

class Fibonacci_Form(forms.Form):
	number=forms.IntegerField()

class media_form(forms.ModelForm):
	class Meta:
		model=media_store
		fields=[
			'title',
			'file'
			]
		
class FileUpload_Form(forms.ModelForm):
	class Meta:
		model=File_Upload
		fields=[
			'Title',
			 'File'
			]

class FileFieldForm(forms.Form):
	file_field=forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple':True}))

class Image_Upload_Form(forms.Form):
		Name=forms.CharField(max_length=20)
		Image=forms.ImageField()
class Login_Form(forms.ModelForm):
		username=forms.CharField(max_length=20)
		password=forms.CharField(label='Password',widget=forms.PasswordInput )
		
		class Meta:
			model=user_login
			fields=('username','password')
class ContactForm(forms.Form):
	name=forms.CharField(max_length=20)
	message=forms.CharField(widget=forms.Textarea)
	
	def send_email(self):
		pass


	
	

mysite/mortgage/views.py
from django.shortcuts import render,get_object_or_404,HttpResponseRedirect
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth import authenticate,login
import datetime
# Create your views here.
from .models import monthly_payment,Remaining_Balance,Monthly_Expenses,Image_Upload
from .forms import Monthly_paymentForm, Monthly_payment_raw_Form,Remaining_Balance_Raw_Form,Monthly_Expenses_Raw_Form,Fibonacci_Form,media_form,FileUpload_Form,FileFieldForm,Image_Upload_Form,Login_Form,ContactForm

from  .my_programs.scripts import *


def monthly_payment_func(request,id):
	Loan= get_object_or_404(monthly_payment,pk=id)
	#principal=413788
	principal=Loan.principal
	Rate=get_object_or_404(monthly_payment,pk=id)
	Interest_rate=Rate.interest
	Years=get_object_or_404(monthly_payment,pk=id)
	duration=Years.duration
	if Interest_rate==0:
		monthly_payment1=principal/(duration*12)
	else:
		r=(Interest_rate/100)/12
		n=duration*12
		monthly_payment1=principal*((r*(1+r)**n)/((1+r)**n-1))
	Monthly_due=get_object_or_404(monthly_payment,pk=id)
	Monthly_due.payment=monthly_payment1
	Monthly_due.save()
	return render(request,'mortgage/mortgage_detail.html' ,{'monthly_payment':monthly_payment1})

def remaining_balance_func(request):
	my_form=Remaining_Balance_Raw_Form()
	#print(my_form)
	if request.method=="POST":
		my_form=Remaining_Balance_Raw_Form(request.POST)
		if my_form.is_valid():
			principal=my_form.cleaned_data['principal']
			interest=my_form.cleaned_data['interest']
			duration=my_form.cleaned_data['duration']
			p       =my_form.cleaned_data['no_of_payments_made']
			print(interest)
			#p=12
			if interest==0:
				Remaining_loan_balance=principal*(1-(p/(duration*12)))
				my_form.cleaned_data['amount_due']=Remaining_loan_balance
				Remaining_Balance.objects.create(**my_form.cleaned_data)
			else:
				r=(interest/100)/12
				n=duration*12
				Remaining_loan_balance=principal*((1+r)**n-(1+r)**p)/((1+r)**n-1)
				my_form.cleaned_data['amount_due']=Remaining_loan_balance
				Remaining_Balance.objects.create(**my_form.cleaned_data)
			print(Remaining_loan_balance)
			return render(request,'mortgage/remaining_balance.html',{'Remaining_balance':Remaining_loan_balance})
	
	else:
			print(my_form.errors)

	context={
		'form':my_form
		}
	return render(request,'mortgage/balance.html',context)



#def loan_details_view(request):
	#form=Monthly_paymentForm(request.POST or None)
	#if form.is_valid():
	#	form.save()
	#context={
	#	'form':form
	#	}
	#return render(request,'mortgage/loan_details.html',context)


def loan_details_view(request):
	my_form=Monthly_payment_raw_Form()
	if request.method=="POST":
		my_form=Monthly_payment_raw_Form(request.POST)
		if my_form.is_valid():
			#my_form.save()
			#print(my_form.cleaned_data)
			#monthly_payment.objects.create(**my_form.cleaned_data)
			principal=my_form.cleaned_data['principal']
			interest=my_form.cleaned_data['interest']
			duration=my_form.cleaned_data['duration']
			if interest==0:
				monthly_payment1=principal/(duration*12)
				my_form.cleaned_data['payment']=monthly_payment1
				monthly_payment.objects.create(**my_form.cleaned_data)
			else:
				r=(interest/100)/12
				n=duration*12
				monthly_payment1=principal*((r*(1+r)**n)/((1+r)**n-1))
				my_form.cleaned_data['payment']=monthly_payment1
				monthly_payment.objects.create(**my_form.cleaned_data)
				return render(request,'mortgage/mortgage_detail.html' ,{'monthly_payment':monthly_payment1})
			#print("monthly payment:",monthly_payment1)
			#print(my_form.cleaned_data)
			#my_form.cleaned_data['payment']=monthly_payment1
			#monthly_payment.objects.create(**my_form.cleaned_data)
			
		else:
			print(my_form.errors)

	context={
		'form':my_form
		}
	return render(request,'mortgage/loan_details.html',context)

def expenses_func(request):
	my_form=Monthly_Expenses_Raw_Form
	if request.method=="POST":
		my_form=Monthly_Expenses_Raw_Form(request.POST)
		if my_form.is_valid():
			#Item  =my_form.cleaned_data['item']
			#Price =my_form.cleanded_data['price']
			print(my_form.cleaned_data)
			output_dict={}
			Monthly_Expenses.objects.create(**my_form.cleaned_data)
			items_list=Monthly_Expenses.objects.all().filter(pub_date__gte=timezone.now()-datetime.timedelta(days=timezone.now().day))
			Total=0
			#print(items_list)
			item_list=list(items_list)
			for data in range(0,len(item_list)):
				queryset=item_list[data]
				#print("Queryset",queryset)
				Total=Total+queryset.price
				output_dict.setdefault(queryset.item,0)
				output_dict[queryset.item]=output_dict[queryset.item]+queryset.price
			print("Total",Total)
			Monthly_Expenses.objects.total=Total
			output_dict['Total']=Total
			
			return render(request,'mortgage/monthly_expenses.html',{'Total_monthly_expenses':output_dict})
		else:
			print(my_form.errors)
	context={
		'form':my_form
		}
	return render(request,'mortgage/monthly_expenses_detail.html',context)


				
			

def monthly_payment_func2(principal,interest,duration):
	if interest==0:
		monthly_payment1=principal/(duration*12)
	else:
		r=(interest/100)/12
		n=duration*12
		monthly_payment1=principal*((r*(1+r)**n)/((1+r)**n-1))
	#Monthly_due=get_object_or_404(monthly_payment,pk=id)
	#Monthly_due.payment=monthly_payment1
	#Monthly_due.save()
	return render(request,'mortgage/mortgage_detail.html' ,{'monthly_payment':monthly_payment1})

def monthly_payment_func3(request):
	my_form=Monthly_payment_raw_Form()
	print(my_form)
	queryset=monthly_payment.objects.all()
	print("{0:^10s}|{1:^10s}|{2:^10s}|{3:^10s}".format("prncipal","interest","duration","payment"))
	print("queryset length:",len(queryset))
	count=0
	output_list=[]
	for item in range(0,len(queryset)):
		count=count+1
		new_list=[]
		x="{0:10d}|{1:10f}|{2:10d}|{3:10f}".format(queryset[item].principal,queryset[item].interest,queryset[item].duration,queryset[item].payment)
		new_list.append(queryset[item].principal)
		new_list.append(queryset[item].interest)
		new_list.append(queryset[item].duration)
		new_list.append(queryset[item].payment)
		output_list.append(new_list)
		print(x)
	print("Output list length :" ,len(output_list))
	return render(request,'mortgage/output_detail.html',{'output':output_list})
	print(count)

def Yearly_Mortagage_Balance(request):
	my_form=Monthly_payment_raw_Form()
	if request.method=="POST":
		my_form=Monthly_payment_raw_Form(request.POST)
		if my_form.is_valid():
			Principal     = my_form.cleaned_data['principal']
			Interest_rate = my_form.cleaned_data['interest']
			duration      = my_form.cleaned_data['duration']
			Total_payment=0
			output_list=[]
			for x in range(1,duration+1):
				BALANCE=rb_func(Principal,Interest_rate,duration)
				PAYMENT=0
				PAYMENT=mp_func(Principal,Interest_rate,duration)
				yearly_payment=12*PAYMENT
				Total_payment=Total_payment+yearly_payment
				#print("Monthly Payment",PAYMENT)
				new_list=[]
				#print(" YEAR:",x," BALANCE: ",BALANCE,"TOTAL PAYMENTS:",Total_payment)
				print(" YEAR{0:5}  BALANCE  {1:10.3f}   TOTAL PAYMENTS  {2:.3f}".format(x,BALANCE,Total_payment))
				Principal=BALANCE
				duration=duration-1
				new_list.append(x)
				new_list.append(round(BALANCE,3))
				new_list.append(round(Total_payment,3))
				output_list.append(new_list)
				x=x+1
			return render(request,'mortgage/yearly_balance_details.html',{'output_list':output_list,'PAYMENT':PAYMENT},)
				
		else:
			print(my_form.errors)
	context={
		'form':my_form
		}
	return render(request,'mortgage/yearly_balance.html',context)


def fibonacci_number(request):
	print(request.user)
	my_form=Fibonacci_Form()
	if request.method=='POST':
		my_form=Fibonacci_Form(request.POST)
		if my_form.is_valid():
			n=my_form.cleaned_data['number']
			output_list=[]
			for k in range(0,n+1):
				if k==0:
					output_list.append(0)
				elif k==1:
					output_list.append(1)
				else:
					output_list.append(output_list[k-2]+output_list[k-1])
				print(output_list)
			return render(request,'mortgage/fibonacci_number.html',{'Fibonacci_number':output_list,'number':n})
		else:
			print(my_form.errors)
	context={'form':my_form}
	return render(request,'mortgage/fibonacci.html',context)
	


##############

def fibonacci_number_1(request):
	form=Login_Form()
	if request.method=='POST':
		user=authenticate(username=request.POST['username'],password=request.POST['password'])
		if user.username is not None:
			print(request.user)
			my_form=Fibonacci_Form()
			if request.method=='POST':
				my_form=Fibonacci_Form(request.POST)
				if my_form.is_valid():
					n=my_form.cleaned_data['number']
					output_list=[]
					for k in range(0,n+1):
						if k==0:
							output_list.append(0)
						elif k==1:
							output_list.append(1)
						else:
							output_list.append(output_list[k-2]+output_list[k-1])
						print(output_list)
					return render(request,'mortgage/fibonacci_number.html',{'Fibonacci_number':output_list,'number':n})
				else:
					print(my_form.errors)
			context={'form':my_form}
			return render(request,'mortgage/fibonacci.html',context)
	return render(request,'mortgage/login.html',{'form':form})

########################
def handle_uploaded_file(f):
	with open('C:\\Users\\anred\\Downloads\\new_file.txt','wb+') as destination:
		for chunk in f.chunks():
			destination.write(chunk)

def media_func(request):
	my_form=media_form()
	if request.method=='POST':
		my_form=media_form(request.POST,request.FILES)
		if my_form.is_valid():
			handle_uploaded_file(request.FILES['file'])
			name=my_form.cleaned_data['title']
			return render(request,'mortgage/media.html',{'Name':'Uloaded sucessfully'})
		else:
			print(my_form.errors)
	context={'form':my_form}
	return render(request,'mortgage/media_initial.html',context)

def file_store(request):
	my_form=FileUpload_Form()
	if request.method=='POST':
		my_form=FileUpload_Form(request.POST,request.FILES)
		if my_form.is_valid():
			
			my_form.save(request.FILES['File'])
			Title=my_form.cleaned_data['Title']
			print("Title is ",Title)

mysite/mortgage/templates/mortgage/balance.html
{% extends 'base.html' %}
 {% block content %}
<h1>Loan details</h1>
<form method="POST"> {% csrf_token %}
{{form.as_p}}
<input type="submit" value="Save">
</head>
 {% endblock %}

mysite/mortgage/templates/mortgage/fibonacci.html
{% extends 'base.html' %}
 {% block content %}
<h1>Fibonnaci number input</h1>
<form  method="POST"> {% csrf_token %}
{{form.as_p}}
<input type="submit" value="Save">
</head>
 {% endblock %}

mysite/mortgage/templates/mortgage/fibonacci_number.html
<!doctype html>
<html>
<head>
<style>
 li {
     text-align:center;
     color:blue;
}
</style>
<h1>Fibonacci number </h1>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
</head>
<body>

<li> Fibonacci number sequence of {{number}}  is 
 {% for item in Fibonacci_number %}
          {{item}}  
        {% endfor%} </li>
  <!{{Fibonacci_number}}>
</body>
</html>

mysite/mortgage/templates/mortgage/file_store.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
<h1> File store details </h1>
<form enctype="multipart/form-data" method="POST"> {% csrf_token %}
<!{{form.as_p}}
<input type="submit" value="Upload">
</form>

{% endblock %}

mysite/mortgage/templates/mortgage/file_upload.html
<!doctype html>
<html>
<head>
<style>
 li {
     text-align:center;
     color:blue;
}
</style>
<h1>File upload status </h1>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
</head>
<body>

<li>    {{ Title }}  uploaded successfully </li>
</body>
</html>

mysite/mortgage/templates/mortgage/loan_details.html
{% extends 'base.html' %}


 {% block content %}
	{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
 <h1> Mortagage Calculator</h1>
 <form method="POST"> {% csrf_token %} 
 {{form.as_p}}
 <input type="submit" value="Save">
 </form>

 {% endblock %}

mysite/mortgage/templates/mortgage/login.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
<h1> Login page </h1>
<!form enctype="multipart/form-data" method="POST"> {% csrf_token %}
<form  method="POST"> {% csrf_token %}
{{form.as_p}}
<input type="submit" value="Save">
</form>

{% endblock %}

mysite/mortgage/templates/mortgage/media.html
<!doctype html>
<html>
<head>
<style>
 li {
     text-align:center;
     color:blue;
}
</style>
<h1>Image details</h1>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
</head>
<body>

<li>  File   {{ Name }}    </li>
<img src={{ Image }} alt=" my image ">
</body>
</html>

mysite/mortgage/templates/mortgage/monthly_expenses.html
<!doctype html>
<html>
<head>
<title> Monthly Expenses </title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">

<h1> Monthly Expenses details </h1>

<style >
       
        table,th,td {
 		     border:1px solid blue;
		     border-collapse:collapse;
		     padding:5px;
		     text-align:left;
</style>

</head>
<body>
   <table>
	<tr>
            <th>Item</th>
            <th>Price</th>
	    <th>Pub_date</th?
         </tr>
			
           {% for k,v in Total_monthly_expenses.items %}
		<tr>
                   <td>{{k}} </td> <td> {{v}}</td> <td>{{x}}</td>
                 </tr>
             {% endfor %}
     </table>

 <!---Total monthly expenses is {{Total_monthly_expenses}}---->
 </body>
<a href="{% url 'mortgage:monthly_expenses' %}"><input type="submit" value="Add more items"> </a>
</html>

mysite/mortgage/templates/mortgage/mortagage_detail.html
<!doctype html>
<html>
<head>
<style>
 li {
     text-align:center;
     color:blue;
}
</style>
<h1>Mortagage calculator</h1>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
</head>
<body>

<li>  Monthly payment is {{ monthly_payment }}  </li>
</body>
</html>

mysite/mortgage/templates/mortgage/mortgage_detail.html
<!doctype html>
<html>
<head>
<style>
 li {
     text-align:center;
     color:blue;
}
</style>
<h1>Mortagage calculator</h1>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
</head>
<body>

<li>  Monthly payment is {{ monthly_payment }}  </li>
</body>
</html>

mysite/mortgage/templates/mortgage/output_detail.html
<!doctype html>
<html>
<head>
<h1>Mortgage calculator</h1>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
<style>
table,th,td{
            border:1px solid grey;
	    border-collapse:collapse;
	    padding:5px;
           }
</style>
</head>
<body>
<ul>
 {% if output|length > 0 %}
	number of items : {{ output|length }}<br>
     <table>
	  <tr>
	      <th>Principal</th>
	      <th>Interest Rate</th>
	      <th>Duration</th>
              <th>Mortgage_Payment</th>
           </tr>
      
   {% for item in output %}
    <tr> 	
     <td>{{  item.0 }} </td> <td>{{  item.1  }}</td><td> {{ item.2 }}</td><td>{{item.3}}</td>
    </tr>
   {% endfor %}
 {% endif %}
</table>
</ul>
</html>

mysite/mortgage/templates/mortgage/remaining_balance.html
{% extends 'base.html' %}
 {% block content %}
 {% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
<h1>Remaining Balance Details</h1>
<body>
<p> Remaining amount due: {{Remaining_balance}}</p>
 </body>
 {% endblock %}

mysite/mortgage/templates/mortgage/yearly_balance.html
{% extends 'base.html' %}

 {% block content %}
 {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mortgage/style.css' %}">
<h1> Yearly baalance details </h1>
<form method="POST"> {% csrf_token %}
{{form.as_p}}
<input type="submit" value="Save">
</form>

{% endblock %}